// Generated by scripts/sync-workflow-audit.mjs from /home/ubuntu/job_search_findings.md. Do not edit by hand.
export const auditSource = "/home/ubuntu/job_search_findings.md";
export const applicationRecords = [
  {
    "messageId": "1a02e6d8a5204e76",
    "sentAt": 1787485320000,
    "employer": "Athulitha Laboratories Private Limited",
    "role": "Production Operator",
    "location": "Jeedimetla, Hyderabad, Telangana",
    "recipient": "hr@athulitha.com",
    "historicalExclusion": false
  },
  {
    "messageId": "1a02cb3b42e0daa0",
    "sentAt": 1787456340000,
    "employer": "Ajanta Pharma",
    "role": "Manufacturing/Packing Associate/Operator",
    "location": "Dahej, Gujarat",
    "recipient": "referral.dhj@ajantapharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "1a02263f0ae78ed7",
    "sentAt": 1787283370000,
    "employer": "Aspiro Pharma Ltd.",
    "role": "Production Operator / Officer – Sterile Injectable Manufacturing",
    "location": "Karakapatla, Hyderabad, Telangana",
    "recipient": "mahesh.e@aspiropharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "1a019d5cb982262e",
    "sentAt": 1787139780000,
    "employer": "Indoco Remedies",
    "role": "Production Operator / Sr. Supervisor – OSD Tablet Packing",
    "location": "Baddi, Himachal Pradesh",
    "recipient": "avinash.kumar@indoco.com",
    "historicalExclusion": false
  },
  {
    "messageId": "1a014ae63b304a4d",
    "sentAt": 1787053320000,
    "employer": "Covalent Laboratories",
    "role": "Production – API Manufacturing",
    "location": "Gundla Machnoor, Sangareddy, Telangana",
    "recipient": "ta@covalentlab.com",
    "historicalExclusion": false
  },
  {
    "messageId": "1a012f040cfc7eb8",
    "sentAt": 1787024100000,
    "employer": "Viyash Scientific Limited Unit-V",
    "role": "Production Chemist / Junior Chemist",
    "location": "Jeedimetla, Telangana",
    "recipient": "kuladeep.m@viyash.com",
    "historicalExclusion": false
  },
  {
    "messageId": "1a012f1714b87941",
    "sentAt": 1787024160000,
    "employer": "Ichor Biologics Pvt. Ltd.",
    "role": "Production – Downstream (DS)",
    "location": "Thurkapally, Shameerpet, Telangana",
    "recipient": "careers@ichor.in",
    "historicalExclusion": false
  },
  {
    "messageId": "1a0111920e98ccaf",
    "sentAt": 1786993314000,
    "employer": "Synokem Lifesciences Pvt. Ltd.",
    "role": "Production Officer / Senior Officer – Granulation",
    "location": "SIDCUL, Haridwar, Uttarakhand",
    "recipient": "jobs@synokempharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "1a010c6db3292828",
    "sentAt": 1786987985000,
    "employer": "Hetero Labs Limited – Unit VI",
    "role": "Production – Injectables (Officer / Executive)",
    "location": "Jadcherla, Telangana",
    "recipient": "Sakhar.V@hetero.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ffedc057899de8",
    "sentAt": 1786687259000,
    "employer": "APL Healthcare Limited – Unit IV",
    "role": "Technical Assistant – Production (OSD/Compression)",
    "location": "Naidupeta/Tirupati",
    "recipient": "naidupetahr@aurobindo.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ffed2be327d59c",
    "sentAt": 1786686651000,
    "employer": "IPCA Laboratories",
    "role": "QA / IPQA Officer",
    "location": "Pologround, Indore",
    "recipient": "abhishekd.parmar@ipca.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ffed242c902076",
    "sentAt": 1786686619000,
    "employer": "Indoco Remedies",
    "role": "OSD Tablet Compression / Production Role",
    "location": "Waluj",
    "recipient": "hr.waluj@indoco.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ffecf83fc2c9e9",
    "sentAt": 1786686439000,
    "employer": "Aizant Drug Research Solutions",
    "role": "IPQA Executive",
    "location": "Hyderabad",
    "recipient": "raghuveera.vutla@aizant.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ffdaec5bd082b0",
    "sentAt": 1786667516000,
    "employer": "Unix Biotech",
    "role": "Production Officer – Tablet & Capsule Manufacturing",
    "location": "Baddi, Himachal Pradesh",
    "recipient": "hr@unixbiotech.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ffdad6bdc6700b",
    "sentAt": 1786667428000,
    "employer": "Rivpra Formulation Pvt. Ltd.",
    "role": "Production Executive – Coating / Compression (OSD)",
    "location": "Haridwar, Uttarakhand",
    "recipient": "career@rivpraformulation.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff999900c34083",
    "sentAt": 1786599018000,
    "employer": "Sunrise Remedies Pvt. Ltd.",
    "role": "Production – OSD Capsule Filling",
    "location": "Santej, Ahmedabad, Gujarat",
    "recipient": "info@sunriseremedies.in",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff947a8aea0d26",
    "sentAt": 1786593650000,
    "employer": "Kashmik Formulation Pvt. Ltd.",
    "role": "Production Officer",
    "location": "Ahmedabad / Sanand GIDC, Gujarat",
    "recipient": "hr@kashmik.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff9238bcfbab77",
    "sentAt": 1786591283000,
    "employer": "Elysium Pharmaceutical Ltd.",
    "role": "Production Officer – Tablet Compression / OSD",
    "location": "Vadodara, Gujarat",
    "recipient": "aman.kumar@elysiumpharma.com",
    "historicalExclusion": true
  },
  {
    "messageId": "19ff9155ce956cf7",
    "sentAt": 1786590354000,
    "employer": "Torrent Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hrvirochannagar@torrentpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff914bb926e46d",
    "sentAt": 1786590312000,
    "employer": "Sun Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "HR.Tandalja@sunpharma.com, careers@sunpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff91473bd01c51",
    "sentAt": 1786590294000,
    "employer": "Intas Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Matoda, Ahmedabad, Gujarat",
    "recipient": "hrd_matoda@intaspharma.com, careers@intaspharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff913dd747a19e",
    "sentAt": 1786590255000,
    "employer": "Alembic Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Vadodara, Gujarat",
    "recipient": "careers@alembic.co.in",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff912a403f59c9",
    "sentAt": 1786590176000,
    "employer": "Lactose India Limited",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "vinayak@lactoseindialimited.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff9125b1d610a3",
    "sentAt": 1786590157000,
    "employer": "Celogen Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr@celogenpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff91144ac3ae55",
    "sentAt": 1786590085000,
    "employer": "Medoz Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr@medozpharmaceuticals.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90fcc0503f33",
    "sentAt": 1786589989000,
    "employer": "Skant",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr@skant.com, career@skant.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90e90864c2d1",
    "sentAt": 1786589909000,
    "employer": "Avenza Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "recruitment@avenzapharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dd0b93899e",
    "sentAt": 1786589859000,
    "employer": "Amneal Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "indiacareers@amneal.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dcac53861c",
    "sentAt": 1786589858000,
    "employer": "Emcure Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "careers@emcure.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dcab214d11",
    "sentAt": 1786589858000,
    "employer": "Intas Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Matoda, Ahmedabad, Gujarat",
    "recipient": "hrd_matoda@intaspharma.com, careers@intaspharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dca7dc6101",
    "sentAt": 1786589858000,
    "employer": "Elysium Pharmaceuticals",
    "role": "Production Officer – Tablet Compression / OSD",
    "location": "Vadodara, Gujarat",
    "recipient": "hr@elysiumpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc9fc40ecb",
    "sentAt": 1786589858000,
    "employer": "Ind-Swift Labs",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr.gbu@indswiftlabs.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc91fafb21",
    "sentAt": 1786589858000,
    "employer": "Lincoln Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Gandhinagar, Gujarat",
    "recipient": "careers@lincolnpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc916b0f3d",
    "sentAt": 1786589858000,
    "employer": "Alembic Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Vadodara, Gujarat",
    "recipient": "careers@alembic.co.in",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc8915f12d",
    "sentAt": 1786589858000,
    "employer": "USV",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hrd@usv.co.in",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc84dfddca",
    "sentAt": 1786589858000,
    "employer": "Innoxel Lifesciences",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Vadodara, Gujarat",
    "recipient": "hr1@innoxells.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc83ae2e1d",
    "sentAt": 1786589857000,
    "employer": "Skant",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr@skant.com, career@skant.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc2da2e1b3",
    "sentAt": 1786589856000,
    "employer": "Torrent Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hrvirochannagar@torrentpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc1f4e29e1",
    "sentAt": 1786589855000,
    "employer": "Glenmark Pharmaceuticals",
    "role": "Production Officer / OSD Tablet Compression",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "india_production@glenmarkpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc1b238d44",
    "sentAt": 1786589856000,
    "employer": "Sun Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "HR.Tandalja@sunpharma.com, careers@sunpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc1a74285f",
    "sentAt": 1786589856000,
    "employer": "Lactose India Limited",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "vinayak@lactoseindialimited.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc0c03b328",
    "sentAt": 1786589855000,
    "employer": "Avenza Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "recruitment@avenzapharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dbf41b8c37",
    "sentAt": 1786589855000,
    "employer": "Celogen Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr@celogenpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dbe2fe932f",
    "sentAt": 1786589855000,
    "employer": "Medoz Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr@medozpharmaceuticals.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff9010fb9dca4b",
    "sentAt": 1786589023000,
    "employer": "Amneal Pharmaceuticals",
    "role": "Manufacturing Officer – OSD Tablet Compression",
    "location": "SEZ Matoda, Ahmedabad, Gujarat",
    "recipient": "chandanid@amneal.com, jyoti.parmar@amneal.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff8fce785c1c24",
    "sentAt": 1786588751000,
    "employer": "Stallion Laboratories Pvt. Ltd.",
    "role": "Production – Tablet Compression / OSD",
    "location": "Ahmedabad, Gujarat",
    "recipient": "paresh.patel@stallionlabs.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff8f1e5b7d8485",
    "sentAt": 1786588029000,
    "employer": "Darshan Healthcare Pvt. Ltd.",
    "role": "Production Officer / Executive",
    "location": "Ankleshwar, Gujarat",
    "recipient": "hr@darshanpharmaindia.in",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff8f18433bf8d0",
    "sentAt": 1786588005000,
    "employer": "Darshan Healthcare Pvt. Ltd.",
    "role": "Production Officer / Executive",
    "location": "Ankleshwar, Gujarat",
    "recipient": "hr@darshanpharmaindia.in",
    "historicalExclusion": false
  }
] as const;
export const runRecords = [
  {
    "id": "audit-run-25",
    "label": "Scheduled evening verified Production, Manufacturing and Biotechnology run — 24 August 2026 (17:03 IST)",
    "date": "24 Aug 2026 (IST)",
    "reviewed": 4,
    "sent": 0,
    "decision": "No application was sent. Zenotech Laboratories, Cohance Lifesciences, Vasant Chemicals and Cipla were safely excluded for incomplete role-level eligibility evidence, biologics-versus-OSD functional uncertainty, stated education mismatch, QR/mobile-only application paths, or absent published email routes. The permanent exclusion remained untouched.",
    "sources": [
      "https://pharmacareer.in/zenotech-laboratories-ltd-a-sun-pharma-group-hiring-for-qaqcqc-microengineeringproduction/",
      "https://pharmacareer.in/cohance-lifesciences-walk-in-interview-30th-aug-for-multiple-positions/",
      "https://pharmacareer.in/walk-in-interview-on-august-29-2026-saturday-for-multiple-positions-at-vasant-chemicals-pvt-ltd/"
    ]
  },
  {
    "id": "audit-run-24",
    "label": "Scheduled verified Production, Manufacturing and Biotechnology run — 24 August 2026 (09:10 IST)",
    "date": "24 Aug 2026 (IST)",
    "reviewed": 5,
    "sent": 0,
    "decision": "No application was sent. Godrej Chemicals, NOCIL, Aarnea Biodome, Ichor Biologics and Haleos Labs were safely excluded for stated education, experience or role mismatch, API functional requirements, absent current email evidence, past-date status, incomplete qualification evidence, or prior company/role outreach. The permanent exclusion remained untouched.",
    "sources": [
      "https://www.jobavailables.com/2026/08/godrej-chemicals-walk-in-interview-on.html",
      "https://www.jobavailables.com/2026/08/aarnea-biodome-hiring-for-production.html",
      "https://www.linkedin.com/posts/chemical-job_nocil-limited-hiring-for-production-utility-activity-7497278498517041153-r2SD"
    ]
  },
  {
    "id": "audit-run-23",
    "label": "Scheduled evening verified Production, Manufacturing and Biotechnology run — 23 August 2026 (17:12 IST)",
    "date": "23 Aug 2026 (IST)",
    "reviewed": 3,
    "sent": 1,
    "decision": "One personalized résumé-backed Athulitha Laboratories Production Operator application was sent after current source, stated any-qualification eligibility, recipient-level and company-level Gmail duplicate checks passed. Bharat Parenterals was excluded for stated qualification mismatch and absent email route, while Apitoria was excluded for past-date status, education/API functional mismatch and absent current email. The permanent exclusion remained untouched.",
    "sources": [
      "https://pharmawisdom.co.in/athulitha-laboratories-walk-in-interviews-on-23rd-to-31st-aug-2026/",
      "https://pharmawisdom.co.in/bharat-parenterals-limited-walk-in-on-24th-25th-aug-2026/"
    ]
  },
  {
    "id": "audit-run-22",
    "label": "Scheduled verified Production, Manufacturing and Biotechnology run — 23 August 2026 (09:09 IST)",
    "date": "23 Aug 2026 (IST)",
    "reviewed": 2,
    "sent": 1,
    "decision": "One personalized résumé-backed Ajanta Pharma Manufacturing/Packing Associate/Operator application was sent after current source, role-fit, recipient-level and company-level Gmail duplicate checks passed. Cadila Pharmaceuticals API Production was excluded because the stated education and API functional experience requirements do not match the documented profile. The permanent exclusion remained untouched.",
    "sources": [
      "https://pharmastuff.org/job/ajanta-pharma-walk-in-interview-jobs",
      "https://pharmawisdom.co.in/cadila-pharmaceuticals-walk-in-on-23rd-aug-2026/"
    ]
  },
  {
    "id": "audit-run-21",
    "label": "Scheduled evening verified Production, Manufacturing and Biotechnology run — 22 August 2026 (17:08 IST)",
    "date": "22 Aug 2026 (IST)",
    "reviewed": 5,
    "sent": 0,
    "decision": "No application was sent. SRF, Bharat Parenterals, Milán Laboratories, Indoco Remedies and Imperium Engineering were safely excluded for stated education or experience mismatch, absent verifiable email or employer evidence, expired/unclear currentness, or recipient/company duplicate protection. The permanent exclusion remained untouched.",
    "sources": [
      "https://pharmabharat.com/bharat-parenterals-is-hiring-for-engineering-administration-purchase-regulatory-affairs-qc-qa-rd-production/",
      "https://pharmastuff.org/job/milan-laboratories-walk-in-interview-pharma-jobs",
      "https://pharmabharat.com/indoco-remedies-is-hiring-for-production-osd-tablet-packing-manufacturing/",
      "https://www.pharmatutor.org/content/august-2026/indoco-remedies-interview-pharma-jobs-in-production-department"
    ]
  },
  {
    "id": "audit-run-20",
    "label": "Scheduled verified Production, Manufacturing and Biotechnology run — 22 August 2026 (09:07 IST)",
    "date": "22 Aug 2026 (IST)",
    "reviewed": 7,
    "sent": 0,
    "decision": "No application was sent. Apitoria, FDC, Pinnacle, Sun Pharma, Maithri Drugs, Eugia and Vamsi Labs were safely excluded for stated qualification or experience mismatch, sterile/API functional mismatch, absent explicit email route, role-scope mismatch, or an earlier delayed delivery/duplicate safeguard. The permanent exclusion remained untouched.",
    "sources": [
      "https://pharmawisdom.co.in/fdc-limited-walk-in-interviews-22nd-aug-2026/",
      "https://pharmawisdom.co.in/pinnacle-life-science-walk-in-on-23rd-aug-2026/",
      "https://pharmawisdom.co.in/maithri-drugs-walk-in-interviews-on-23rd-aug-2026/",
      "https://pharmawisdom.co.in/eugia-pharma-walk-ins-for-qa-ipqa-production-departments-on-23rd-aug-2026/",
      "https://pharmawisdom.co.in/vamsi-labs-ltd-walk-in-interviews-on-22nd-24th-aug-2026/"
    ]
  },
  {
    "id": "audit-run-19",
    "label": "Verified Production, Manufacturing and Biotechnology follow-up — 21 August 2026 (17:08 IST)",
    "date": "21 Aug 2026 (IST)",
    "reviewed": 10,
    "sent": 0,
    "decision": "No application was sent. Global Calcium, Verdant, Felix, Sunrise, Yeluri, Metrochem, Lupin, Micro Labs, Aurobindo and Bharat Parenterals/local social-source leads were safely excluded for stated qualification or experience mismatch, sterile/API functional mismatch, missing explicit email or role-level evidence, incomplete/stale source evidence, or prior substantially similar company outreach. The permanent exclusion remained untouched.",
    "sources": [
      "https://pharmabharat.com/global-calcium-is-hiring-freshers-for-apprentice-production/",
      "https://pharmawisdom.co.in/felix-generics-walk-in-on-21st-aug-2026/",
      "https://pharmabharat.com/lupin-manufacturing-solutions-is-hiring-for-production-and-quality-control/",
      "https://pharmastuff.org/job/micro-labs-production-packing-engineering-jobs",
      "https://pharmastuff.org/job/aurobindo-pharma-walk-in-interview-production-qc-qa"
    ]
  },
  {
    "id": "audit-run-18",
    "label": "Verified Production, Manufacturing and Biotechnology run — 21 August 2026 (09:06 IST)",
    "date": "21 Aug 2026 (IST)",
    "reviewed": 17,
    "sent": 1,
    "decision": "One personalized résumé-backed application was sent to Aspiro Pharma after empty recipient-level and company-level Gmail duplicate checks. The message transparently disclosed Balaji's Diploma in Biotechnology, OSD-only production background, immediate availability and willingness to transition to sterile manufacturing. Sixteen other current leads were safely excluded for qualification or experience mismatch, functional mismatch, absent/incomplete role or email evidence, prior contact, an unconfirmed prior Ciron delivery safeguard, or expiring event timing. The permanent exclusion remained untouched.",
    "sources": [
      "https://pharmajobalert.in/aspiro-pharma-ltd-walk-in-drive-23-august-2026-itidiplomabscmscbpharmmpharmb-tech-for-multiple-positions/",
      "https://pharmastuff.org/job/ciron-drugs-walk-in-interview-qc-qa-production",
      "https://pharmajobalert.in/jubilant-generics-ltd-walk-in-on-22nd-23rd-aug-2026-iti-diploma-102-m-sc-b-sc-b-pharm-m-pharm-for-multiple-positions/",
      "https://pharmajobalert.in/aarti-pharmalabs-ltd-walk-in-on-23rd-august-2026-sunday-for-multiple-positions/"
    ]
  },
  {
    "id": "audit-run-17",
    "label": "Verified Production and Manufacturing follow-up run — 20 August 2026 (17:13 IST)",
    "date": "20 Aug 2026 (IST)",
    "reviewed": 14,
    "sent": 0,
    "decision": "No application was sent. Pinnacle Life Science Baddi Compression/Granulation was the only new role with reasonable OSD functional fit and a current public company email; duplicate checks were empty, but the personalized résumé-backed delivery request remained unconfirmed and was stopped after re-check. Lupin, Zydus, Metrochem, MSN, Neuland, Aspiro, BioMatrix, Terratech, Troikaa, Haleos, OneSource and Synokem were safely excluded for stated qualification/experience or functional mismatch, stale/closed status, incomplete role evidence, no email route, role scope mismatch, or duplicate protection. The permanent exclusion remained untouched.",
    "sources": [
      "https://pharmajobalert.in/pinnacle-life-science-pvt-ltd-walk-in-on-23rd-august-sunday-for-qaqcitehsproduction/amp/",
      "https://pharmarising.in/zydus-lifesciences-walk-in-interview-august-2026/",
      "https://pharmabharat.com/aspiro-pharma-limited-is-hiring-for-production-engineering-job/",
      "https://pharmabharat.org/neuland-laboratories-hiring-for-production-quality-control-quality-assurance-2/"
    ]
  },
  {
    "id": "audit-run-16",
    "label": "Verified Production and Manufacturing run — 20 August 2026 (09:13 IST)",
    "date": "20 Aug 2026 (IST)",
    "reviewed": 10,
    "sent": 0,
    "decision": "No application was sent. Ciron Drugs Boisar Packing/Manufacturing was the only reasonably eligible new published-email route; recipient and company Gmail searches were clean, but the résumé-backed request remained unconfirmed in the Gmail delivery safeguard and was stopped after a follow-up recipient search remained empty. Stallion, IPCA, Medley, Felix, Haleos, FDC, Saga, Naprod and Aarti were safely skipped for duplicate protection, functional or qualification mismatch, missing role-level evidence, or missing email route. The permanent exclusion remained untouched.",
    "sources": [
      "https://pharmastuff.org/job/ciron-drugs-walk-in-interview-qc-qa-production",
      "https://pharmastuff.org/job/medley-pharmaceuticals-production-qc-recruitment",
      "https://pharmajobalert.in/saga-lifesciences-walk-in-on-21st-and-22nd-august-for-qaqcaqarapurchaseibdpahrproductionpackingengineering/amp/",
      "https://pharmajobalert.in/aarti-pharmalabs-ltd-walk-in-on-23rd-august-2026-sunday-for-multiple-positions/amp/"
    ]
  },
  {
    "id": "audit-run-15",
    "label": "Verified Production and Biotechnology follow-up run — 19 August 2026 (17:13 IST)",
    "date": "19 Aug 2026 (IST)",
    "reviewed": 20,
    "sent": 1,
    "decision": "Indoco Remedies Baddi OSD Tablet Packing was sent after a current published recruitment email, a recipient-specific empty Gmail search, and separate-role/company-history review. Nineteen other leads were safely skipped for stated qualification, functional experience, minimum-experience, past-date, insufficient-evidence, no-email-route, or duplicate-protection safeguards. The permanent exclusion remained untouched.",
    "sources": [
      "https://pharmabharat.org/indoco-remedies-hiring-for-production/",
      "https://www.facebook.com/LincolnPharmaceuticalsLimited/posts/-hiring-alert-mega-walk-in-drive-are-you-looking-for-exciting-career-opportuniti/1374500591464230/",
      "https://pharmabharat.com/aurobindo-pharma-is-hiring-for-production-packing-qc-qa/",
      "https://pharmabharat.com/usv-private-limited-is-hiring-freshers-experienced-for-engineering-production-packing-qc/",
      "https://pharmajobalert.in/jubilant-generics-ltd-walk-in-on-22nd-23rd-aug-2026-iti-diploma-102-m-sc-b-sc-b-pharm-m-pharm-for-multiple-positions/amp/"
    ]
  },
  {
    "id": "audit-run-14",
    "label": "Verified Production and Biotechnology run — 19 August 2026 (09:11 IST)",
    "date": "19 Aug 2026 (IST)",
    "reviewed": 8,
    "sent": 0,
    "decision": "No application was sent. SRF, Hetero, Ajanta, Arovea, Sun Pharma, Bharat Biotech, Granules and Concord were safely skipped for stated qualification or functional mismatch, a missing email route, past-date status, or duplicate-company/role protection. The permanent exclusion remained untouched.",
    "sources": [
      "https://pharmabharat.org/hetero-hiring-for-production-quality-assurance-quality-control/",
      "https://pharmabharat.org/ajanta-pharma-hiring-for-manufacturing-qa-qc-maintenance-stores-it/",
      "https://pharmajobalert.in/arovea-formulations-pvt-ltd-we-are-hiring-freshers-experience-for-qaqcaccountsdispensingproductionitistore/amp/",
      "https://pharmacareer.in/sun-pharmaceuticals-walk-in-on-20th-august-2026-freshers-experience/"
    ]
  },
  {
    "id": "audit-run-13",
    "label": "Verified Production and Biotechnology run — 18 August 2026 (17:12 IST)",
    "date": "18 Aug 2026 (IST)",
    "reviewed": 7,
    "sent": 1,
    "decision": "Covalent Laboratories Production was sent after two current public sources corroborated the company-domain contact and Gmail returned no duplicate. Alivus, Dr. Reddy’s, Hetero, Piramal, Apothecon and Viyash were safely skipped for specialised qualification/API mismatch, fresher-only criteria, seniority/formulation-development mismatch, incomplete contact attribution, or duplicate protection.",
    "sources": [
      "https://pharmajobalert.in/covalent-laboratories-walk-in-22nd-august-2026-freshers-experience/amp/",
      "https://pharmawisdom.co.in/covalent-laboratories-walk-in-interviews-for-freshers-experienced-in-production-solvent-recovery-on-22nd-aug-2026/",
      "https://pharmabharat.org/alivus-life-sciences-hiring-for-production/",
      "https://pharmawisdom.co.in/hetero-walk-in-drive-on-22nd-aug-2026/"
    ]
  },
  {
    "id": "audit-run-12",
    "label": "Verified Production and Biotechnology run — 18 August 2026",
    "date": "18 Aug 2026 (IST)",
    "reviewed": 9,
    "sent": 2,
    "decision": "Two independently corroborated, currently open production routes were sent after clean Gmail duplicate checks: Viyash Unit-V Production and Ichor Biologics Production–Downstream. Both emails disclosed the candidate’s Diploma in Biotechnology because the postings specify different formal qualifications. Lupin, Sunrise, SunGlow, Lincoln, Zydus, Ipca, and InvaGen were safely skipped for experience/qualification mismatch, duplicate protection, missing email route, incomplete evidence, past date, or geography.",
    "sources": [
      "https://pharmabharat.org/viyash-scientific-limited-hiring-for-production/",
      "https://pharmabharat.org/freshers-needed-in-qc-microbiology-production-downstream-at-ichor-biologics-pvt-ltd/",
      "https://pharmabharat.org/lupin-hiring-for-quality-control-production/"
    ]
  },
  {
    "id": "audit-run-11",
    "label": "Verified production and biotech follow-up run — 17 August 2026",
    "date": "17 Aug 2026 (IST)",
    "reviewed": 2,
    "sent": 1,
    "decision": "Synokem’s current Granulation Officer/Sr. Officer route met the stated 2–4 year experience criterion and had no Gmail duplicate; the application disclosed the Diploma in Biotechnology because formal qualification was unclear. USV Production roles required 10–12 years at Assistant Manager level.",
    "sources": [
      "https://pharmabharat.com/synokem-lifesciences-is-hiring-for-engineering-production-and-quality-control/",
      "https://pharmabharat.org/usv-hiring-for-production-quality-control-engineering/"
    ]
  },
  {
    "id": "audit-run-10",
    "label": "Verified Intas OSD Packing duplicate check — 17 August 2026",
    "date": "17 Aug 2026 (IST)",
    "reviewed": 1,
    "sent": 0,
    "decision": "The current Diploma/ITI OSD Packing route was eligible on stated experience but was not emailed because Gmail history confirmed a substantially similar 13 August Intas Production Officer / OSD Manufacturing application to the company’s Matoda HR/careers contacts.",
    "sources": [
      "https://www.instagram.com/jobinfobysuhani/reel/DcH1rpSykhv/",
      "https://pharmabharat.com/intas-pharma-is-hiring-for-manufacturing-packing-qa-qc-and-engineering/"
    ]
  },
  {
    "id": "audit-run-9",
    "label": "Verified production follow-up scan — 17 August 2026",
    "date": "17 Aug 2026 (IST)",
    "reviewed": 7,
    "sent": 0,
    "decision": "No new qualified non-duplicate recipient was identified. Aurobindo/APL and Amneal were duplicate or past-date; the other opportunities had verified qualification, seniority, role-specificity, or contact-clarity mismatches.",
    "sources": [
      "https://pharmabharat.com/aurobindo-pharma-is-hiring-for-production-packing-qc-qa/",
      "https://pharmajobalert.in/walk-in-on-18th-aug-2026-for-qaqcproduction-at-v-ensure-pharma-technologies-pvt-ltd/",
      "https://pharmajobalert.in/apcotex-industries-ltd-walk-in-on-august-18-2026-for-multiple-positions/",
      "https://pharmajobalert.in/walk-in-on-august-18th-19th-2026-itidiplomabscb-commbab-pharmmpharmb-tech-at-vital-therapeutics-and-formulations-pvt-ltd/"
    ]
  },
  {
    "id": "audit-run-8",
    "label": "Verified current Production / Biotechnology scan — 17 August 2026",
    "date": "17 Aug 2026 (IST)",
    "reviewed": 10,
    "sent": 0,
    "decision": "No new qualified non-duplicate email recipient was identified. The reviewed roles had a stated education, experience, functional-fit, or application-clarity mismatch; no eligibility was inferred for the Diploma in Biotechnology.",
    "sources": [
      "https://pharmabharat.org/lupin-hiring-for-quality-control-production/",
      "https://pharmabharat.org/aspiro-pharma-hiring-for-production-instrumentation-and-engineering/",
      "https://pharmabharat.org/usv-hiring-for-production-quality-control-engineering/",
      "https://pharmacareer.in/rusan-pharma-ltd-is-looking-for-enthusiastic-fresher-and-experienced/",
      "https://pharmacareer.in/urgent-walk-in-freshers-experience-for-multiple-positions-at-smith-kenner-pharmaceuticals-pvt-ltd/"
    ]
  },
  {
    "id": "audit-run-7",
    "label": "Verified current-vacancy scan — 17 August 2026",
    "date": "17 Aug 2026 (IST)",
    "reviewed": 4,
    "sent": 0,
    "decision": "Lincoln and Akums had qualification mismatch, Bharat Biotech’s accessible criteria did not establish an Officer-level Diploma route, and Sri Krishna was past-date. No qualified non-duplicate email recipient was identified.",
    "sources": [
      "https://www.facebook.com/LincolnPharmaceuticalsLimited/posts/-hiring-alert-walk-in-intervieware-you-an-experienced-qa-qc-or-production-profes/1368531012061188/",
      "https://www.instagram.com/reel/DcGl0xgSnPB/",
      "https://www.instagram.com/reel/DcBTGMdJZyP/",
      "https://www.instagram.com/hiring_updateinfo/reel/Db8s2xzpKTH/"
    ]
  },
  {
    "id": "audit-run-6",
    "label": "Verified production search and application run — 17 August 2026",
    "date": "17 Aug 2026 (IST)",
    "reviewed": 4,
    "sent": 1,
    "decision": "Hetero met the published Diploma and 2–8 year Production criteria with transparent OSD-versus-injectables disclosure. Concord and Viyash had qualification/experience mismatches, while MSN was past-date.",
    "sources": [
      "https://pharmabharat.org/concord-biotech-hiring-for-production-and-quality-control/",
      "https://pharmabharat.org/viyash-scientific-limited-hiring-for-production/",
      "https://pharmabharat.org/freshers-needed-in-production-at-msn-group/",
      "https://pharmabharat.org/hetero-hiring-for-production-quality-assurance-quality-control/"
    ]
  },
  {
    "id": "audit-run-1",
    "label": "Scheduled verified run — 15 August 2026 (additional scan)",
    "date": "15 Aug 2026 (IST)",
    "reviewed": 4,
    "sent": 0,
    "decision": "No new qualified, non-duplicate email recipient was identified. Experience mismatch, missing published contacts, stale roles and duplicate outreach were all rejected.",
    "sources": [
      "https://pharmarising.in/acme-generics-recruitment-august-2026/",
      "https://pharmastuff.org/job/beta-drugs-multiple-positions-baddi",
      "https://pharmabharat.com/stallion-laboratories-is-hiring-for-production-warehouse-packing-qc-engineering-qa-adl/"
    ]
  },
  {
    "id": "audit-run-2",
    "label": "Scheduled verified run — 15 August 2026",
    "date": "15 Aug 2026 (IST)",
    "reviewed": 4,
    "sent": 0,
    "decision": "Bharat Parenterals and BETA Drugs had qualification mismatch; Marksans was past-date; Stallion was a duplicate; HOF Pharma used an unverified generic contact.",
    "sources": [
      "https://dmc-education.com/2026/08/14/bharat-parenterals-limited-recruitment-2026-walk-in-interview-for-engineering-pharma-qa-qc-regulatory-affairs-jobs/",
      "https://pharmabharat.com/stallion-laboratories-is-hiring-for-production-warehouse-packing-qc-engineering-qa-adl/"
    ]
  },
  {
    "id": "audit-run-3",
    "label": "Additional current scan — 14 August 2026",
    "date": "14 Aug 2026 (IST)",
    "reviewed": 5,
    "sent": 0,
    "decision": "Ajanta, Sun Pharma, AMGIS, Allrite and BETA Drugs were safely skipped because a role-relevant email channel, stated eligibility, or OSD fit was absent.",
    "sources": [
      "https://pharmabharat.com/ajanta-pharma-is-hiring-for-rm-pm-fg/",
      "https://pharmacareer.in/sun-pharmaceuticals-walk-in-on-august-16-2026-for-qaqcproductionmicroengineeringwarehouse/"
    ]
  },
  {
    "id": "audit-run-4",
    "label": "Additional application run — 13 August 2026",
    "date": "13 Aug 2026 (IST)",
    "reviewed": 4,
    "sent": 2,
    "decision": "Rivpra Formulation and Unix Biotech met the experience, role and published-contact tests. BETA Drugs and Ronam Healthcare did not.",
    "sources": [
      "https://pharmabharat.org/rivpra-formulation-hiring-for-production-quality-assurance-quality-control/",
      "https://pharmacareer.in/unix-biotech-urgent-recruitment-for-qaqcproductionstore-pm-rm/"
    ]
  },
  {
    "id": "audit-run-5",
    "label": "Biotechnology / pharma production immediate run — 13 August 2026",
    "date": "13 Aug 2026 (IST)",
    "reviewed": 7,
    "sent": 1,
    "decision": "Sunrise Remedies met the functional OSD experience criteria with transparent Diploma in Biotechnology disclosure. Concord, AMI, Lupin, Lincoln, Mercury and Lyka did not meet the combined criteria.",
    "sources": [
      "https://pharmastuff.org/job/sunrise-remedies-recruitment",
      "https://www.jobavailables.com/2026/08/concord-biotech-jobs-in-ahmedabad.html"
    ]
  }
] as const;
