// Generated by scripts/sync-workflow-audit.mjs from /home/ubuntu/job_search_findings.md. Do not edit by hand.
export const auditSource = "/home/ubuntu/job_search_findings.md";
export const applicationRecords = [
  {
    "messageId": "1a010c6db3292828",
    "sentAt": 1786987985000,
    "employer": "Hetero Labs Limited – Unit VI",
    "role": "Production – Injectables (Officer / Executive)",
    "location": "Jadcherla, Telangana",
    "recipient": "Sakhar.V@hetero.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ffedc057899de8",
    "sentAt": 1786687259000,
    "employer": "APL Healthcare Limited – Unit IV",
    "role": "Technical Assistant – Production (OSD/Compression)",
    "location": "Naidupeta/Tirupati",
    "recipient": "naidupetahr@aurobindo.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ffed2be327d59c",
    "sentAt": 1786686651000,
    "employer": "IPCA Laboratories",
    "role": "QA / IPQA Officer",
    "location": "Pologround, Indore",
    "recipient": "abhishekd.parmar@ipca.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ffed242c902076",
    "sentAt": 1786686619000,
    "employer": "Indoco Remedies",
    "role": "OSD Tablet Compression / Production Role",
    "location": "Waluj",
    "recipient": "hr.waluj@indoco.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ffecf83fc2c9e9",
    "sentAt": 1786686439000,
    "employer": "Aizant Drug Research Solutions",
    "role": "IPQA Executive",
    "location": "Hyderabad",
    "recipient": "raghuveera.vutla@aizant.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ffdaec5bd082b0",
    "sentAt": 1786667516000,
    "employer": "Unix Biotech",
    "role": "Production Officer – Tablet & Capsule Manufacturing",
    "location": "Baddi, Himachal Pradesh",
    "recipient": "hr@unixbiotech.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ffdad6bdc6700b",
    "sentAt": 1786667428000,
    "employer": "Rivpra Formulation Pvt. Ltd.",
    "role": "Production Executive – Coating / Compression (OSD)",
    "location": "Haridwar, Uttarakhand",
    "recipient": "career@rivpraformulation.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff999900c34083",
    "sentAt": 1786599018000,
    "employer": "Sunrise Remedies Pvt. Ltd.",
    "role": "Production – OSD Capsule Filling",
    "location": "Santej, Ahmedabad, Gujarat",
    "recipient": "info@sunriseremedies.in",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff947a8aea0d26",
    "sentAt": 1786593650000,
    "employer": "Kashmik Formulation Pvt. Ltd.",
    "role": "Production Officer",
    "location": "Ahmedabad / Sanand GIDC, Gujarat",
    "recipient": "hr@kashmik.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff9238bcfbab77",
    "sentAt": 1786591283000,
    "employer": "Elysium Pharmaceutical Ltd.",
    "role": "Production Officer – Tablet Compression / OSD",
    "location": "Vadodara, Gujarat",
    "recipient": "aman.kumar@elysiumpharma.com",
    "historicalExclusion": true
  },
  {
    "messageId": "19ff9155ce956cf7",
    "sentAt": 1786590354000,
    "employer": "Torrent Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hrvirochannagar@torrentpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff914bb926e46d",
    "sentAt": 1786590312000,
    "employer": "Sun Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "HR.Tandalja@sunpharma.com, careers@sunpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff91473bd01c51",
    "sentAt": 1786590294000,
    "employer": "Intas Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Matoda, Ahmedabad, Gujarat",
    "recipient": "hrd_matoda@intaspharma.com, careers@intaspharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff913dd747a19e",
    "sentAt": 1786590255000,
    "employer": "Alembic Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Vadodara, Gujarat",
    "recipient": "careers@alembic.co.in",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff912a403f59c9",
    "sentAt": 1786590176000,
    "employer": "Lactose India Limited",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "vinayak@lactoseindialimited.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff9125b1d610a3",
    "sentAt": 1786590157000,
    "employer": "Celogen Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr@celogenpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff91144ac3ae55",
    "sentAt": 1786590085000,
    "employer": "Medoz Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr@medozpharmaceuticals.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90fcc0503f33",
    "sentAt": 1786589989000,
    "employer": "Skant",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr@skant.com, career@skant.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90e90864c2d1",
    "sentAt": 1786589909000,
    "employer": "Avenza Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "recruitment@avenzapharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dd0b93899e",
    "sentAt": 1786589859000,
    "employer": "Amneal Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "indiacareers@amneal.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dcac53861c",
    "sentAt": 1786589858000,
    "employer": "Emcure Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "careers@emcure.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dcab214d11",
    "sentAt": 1786589858000,
    "employer": "Intas Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Matoda, Ahmedabad, Gujarat",
    "recipient": "hrd_matoda@intaspharma.com, careers@intaspharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dca7dc6101",
    "sentAt": 1786589858000,
    "employer": "Elysium Pharmaceuticals",
    "role": "Production Officer – Tablet Compression / OSD",
    "location": "Vadodara, Gujarat",
    "recipient": "hr@elysiumpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc9fc40ecb",
    "sentAt": 1786589858000,
    "employer": "Ind-Swift Labs",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr.gbu@indswiftlabs.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc91fafb21",
    "sentAt": 1786589858000,
    "employer": "Lincoln Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Gandhinagar, Gujarat",
    "recipient": "careers@lincolnpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc916b0f3d",
    "sentAt": 1786589858000,
    "employer": "Alembic Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Vadodara, Gujarat",
    "recipient": "careers@alembic.co.in",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc8915f12d",
    "sentAt": 1786589858000,
    "employer": "USV",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hrd@usv.co.in",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc84dfddca",
    "sentAt": 1786589858000,
    "employer": "Innoxel Lifesciences",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Vadodara, Gujarat",
    "recipient": "hr1@innoxells.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc83ae2e1d",
    "sentAt": 1786589857000,
    "employer": "Skant",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr@skant.com, career@skant.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc2da2e1b3",
    "sentAt": 1786589856000,
    "employer": "Torrent Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hrvirochannagar@torrentpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc1f4e29e1",
    "sentAt": 1786589855000,
    "employer": "Glenmark Pharmaceuticals",
    "role": "Production Officer / OSD Tablet Compression",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "india_production@glenmarkpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc1b238d44",
    "sentAt": 1786589856000,
    "employer": "Sun Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "HR.Tandalja@sunpharma.com, careers@sunpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc1a74285f",
    "sentAt": 1786589856000,
    "employer": "Lactose India Limited",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "vinayak@lactoseindialimited.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dc0c03b328",
    "sentAt": 1786589855000,
    "employer": "Avenza Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "recruitment@avenzapharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dbf41b8c37",
    "sentAt": 1786589855000,
    "employer": "Celogen Pharma",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr@celogenpharma.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff90dbe2fe932f",
    "sentAt": 1786589855000,
    "employer": "Medoz Pharmaceuticals",
    "role": "Production Officer / OSD Manufacturing",
    "location": "Location not recorded in job_search_findings.md",
    "recipient": "hr@medozpharmaceuticals.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff9010fb9dca4b",
    "sentAt": 1786589023000,
    "employer": "Amneal Pharmaceuticals",
    "role": "Manufacturing Officer – OSD Tablet Compression",
    "location": "SEZ Matoda, Ahmedabad, Gujarat",
    "recipient": "chandanid@amneal.com, jyoti.parmar@amneal.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff8fce785c1c24",
    "sentAt": 1786588751000,
    "employer": "Stallion Laboratories Pvt. Ltd.",
    "role": "Production – Tablet Compression / OSD",
    "location": "Ahmedabad, Gujarat",
    "recipient": "paresh.patel@stallionlabs.com",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff8f1e5b7d8485",
    "sentAt": 1786588029000,
    "employer": "Darshan Healthcare Pvt. Ltd.",
    "role": "Production Officer / Executive",
    "location": "Ankleshwar, Gujarat",
    "recipient": "hr@darshanpharmaindia.in",
    "historicalExclusion": false
  },
  {
    "messageId": "19ff8f18433bf8d0",
    "sentAt": 1786588005000,
    "employer": "Darshan Healthcare Pvt. Ltd.",
    "role": "Production Officer / Executive",
    "location": "Ankleshwar, Gujarat",
    "recipient": "hr@darshanpharmaindia.in",
    "historicalExclusion": false
  }
] as const;
export const runRecords = [
  {
    "id": "audit-run-7",
    "label": "Verified current-vacancy scan — 17 August 2026",
    "date": "17 Aug 2026 (IST)",
    "reviewed": 4,
    "sent": 0,
    "decision": "Lincoln and Akums had qualification mismatch, Bharat Biotech’s accessible criteria did not establish an Officer-level Diploma route, and Sri Krishna was past-date. No qualified non-duplicate email recipient was identified.",
    "sources": [
      "https://www.facebook.com/LincolnPharmaceuticalsLimited/posts/-hiring-alert-walk-in-intervieware-you-an-experienced-qa-qc-or-production-profes/1368531012061188/",
      "https://www.instagram.com/reel/DcGl0xgSnPB/",
      "https://www.instagram.com/reel/DcBTGMdJZyP/",
      "https://www.instagram.com/hiring_updateinfo/reel/Db8s2xzpKTH/"
    ]
  },
  {
    "id": "audit-run-6",
    "label": "Verified production search and application run — 17 August 2026",
    "date": "17 Aug 2026 (IST)",
    "reviewed": 4,
    "sent": 1,
    "decision": "Hetero met the published Diploma and 2–8 year Production criteria with transparent OSD-versus-injectables disclosure. Concord and Viyash had qualification/experience mismatches, while MSN was past-date.",
    "sources": [
      "https://pharmabharat.org/concord-biotech-hiring-for-production-and-quality-control/",
      "https://pharmabharat.org/viyash-scientific-limited-hiring-for-production/",
      "https://pharmabharat.org/freshers-needed-in-production-at-msn-group/",
      "https://pharmabharat.org/hetero-hiring-for-production-quality-assurance-quality-control/"
    ]
  },
  {
    "id": "audit-run-1",
    "label": "Scheduled verified run — 15 August 2026 (additional scan)",
    "date": "15 Aug 2026 (IST)",
    "reviewed": 4,
    "sent": 0,
    "decision": "No new qualified, non-duplicate email recipient was identified. Experience mismatch, missing published contacts, stale roles and duplicate outreach were all rejected.",
    "sources": [
      "https://pharmarising.in/acme-generics-recruitment-august-2026/",
      "https://pharmastuff.org/job/beta-drugs-multiple-positions-baddi",
      "https://pharmabharat.com/stallion-laboratories-is-hiring-for-production-warehouse-packing-qc-engineering-qa-adl/"
    ]
  },
  {
    "id": "audit-run-2",
    "label": "Scheduled verified run — 15 August 2026",
    "date": "15 Aug 2026 (IST)",
    "reviewed": 4,
    "sent": 0,
    "decision": "Bharat Parenterals and BETA Drugs had qualification mismatch; Marksans was past-date; Stallion was a duplicate; HOF Pharma used an unverified generic contact.",
    "sources": [
      "https://dmc-education.com/2026/08/14/bharat-parenterals-limited-recruitment-2026-walk-in-interview-for-engineering-pharma-qa-qc-regulatory-affairs-jobs/",
      "https://pharmabharat.com/stallion-laboratories-is-hiring-for-production-warehouse-packing-qc-engineering-qa-adl/"
    ]
  },
  {
    "id": "audit-run-3",
    "label": "Additional current scan — 14 August 2026",
    "date": "14 Aug 2026 (IST)",
    "reviewed": 5,
    "sent": 0,
    "decision": "Ajanta, Sun Pharma, AMGIS, Allrite and BETA Drugs were safely skipped because a role-relevant email channel, stated eligibility, or OSD fit was absent.",
    "sources": [
      "https://pharmabharat.com/ajanta-pharma-is-hiring-for-rm-pm-fg/",
      "https://pharmacareer.in/sun-pharmaceuticals-walk-in-on-august-16-2026-for-qaqcproductionmicroengineeringwarehouse/"
    ]
  },
  {
    "id": "audit-run-4",
    "label": "Additional application run — 13 August 2026",
    "date": "13 Aug 2026 (IST)",
    "reviewed": 4,
    "sent": 2,
    "decision": "Rivpra Formulation and Unix Biotech met the experience, role and published-contact tests. BETA Drugs and Ronam Healthcare did not.",
    "sources": [
      "https://pharmabharat.org/rivpra-formulation-hiring-for-production-quality-assurance-quality-control/",
      "https://pharmacareer.in/unix-biotech-urgent-recruitment-for-qaqcproductionstore-pm-rm/"
    ]
  },
  {
    "id": "audit-run-5",
    "label": "Biotechnology / pharma production immediate run — 13 August 2026",
    "date": "13 Aug 2026 (IST)",
    "reviewed": 7,
    "sent": 1,
    "decision": "Sunrise Remedies met the functional OSD experience criteria with transparent Diploma in Biotechnology disclosure. Concord, AMI, Lupin, Lincoln, Mercury and Lyka did not meet the combined criteria.",
    "sources": [
      "https://pharmastuff.org/job/sunrise-remedies-recruitment",
      "https://www.jobavailables.com/2026/08/concord-biotech-jobs-in-ahmedabad.html"
    ]
  }
] as const;
